### PR TITLE
README: Add section about using Cloudflare

### PR DESCRIPTION
**Pull request by NunoAlexandre**

### CODE REVIEW

**Review by geigerzaehler — COMMENTED** [review]
If we want to keep caching, then we should also explain how to invalidate caches as part of the deployment. I’d would advise though to disable caching for now to save us this extra work.

**Comment by NunoAlexandre** [comment]
I have just enabled the Development Mode in the Caching Settings. What further information would you like to have here? I always use Cloudflare in front of all domains I manage so I'm too biased.

**Review by geigerzaehler — APPROVED** [review]
The existing documentation is enough if no extra steps are required for deployment. The idea behind adding this is to ensure that a person who has not overheard this in a conversation or is joining the team has enough information to be able to work with the deployments.

**Comment by NunoAlexandre** [comment]
> The existing documentation is enough if no extra steps are required for deployment. The idea behind adding this is to ensure that a person who has not overheard this in a conversation or is joining the team has enough information to be able to work with the deployments.

Absolutely :ok_hand:

**Pull request merged**
